server:
  port: 8080

spring:
  application:
    name: websocket-server

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8081/.well-known/jwks.json

auth:
  jwe-key-value: classpath:simple.priv
